# Generated by Django 2.0.7 on 2019-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
